name: Release

on:
  push:
    tags:
      - 'v*'

env:
  NODE_VERSION: '18'
  RUST_VERSION: '1.75'

jobs:
  # Site Bruna Release
  site-bruna-release:
    name: Site Bruna Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm run install --workspace=site-bruna

      - name: Build site
        run: npm run build --workspace=site-bruna

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./site-bruna
          scope: ${{ secrets.VERCEL_ORG_ID }}

  # App Bruna Release
  app-bruna-release:
    name: App Bruna Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            app-bruna/src-tauri/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install dependencies
        run: |
          npm ci
          npm run install --workspace=app-bruna

      - name: Install Tauri CLI
        run: npm install -g @tauri-apps/cli

      - name: Build frontend
        run: npm run build --workspace=app-bruna

      - name: Build Tauri app
        run: |
          cd app-bruna
          npm run tauri:build

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            app-bruna/src-tauri/target/release/bundle/msi/*.msi
            app-bruna/src-tauri/target/release/bundle/nsis/*.exe
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Windows Build
  app-bruna-windows:
    name: App Bruna Windows Build
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - name: Install dependencies
        run: |
          npm ci
          npm run install --workspace=app-bruna

      - name: Install Tauri CLI
        run: npm install -g @tauri-apps/cli

      - name: Build frontend
        run: npm run build --workspace=app-bruna

      - name: Build Tauri app
        run: |
          cd app-bruna
          npm run tauri:build

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-bruna-windows
          path: app-bruna/src-tauri/target/release/bundle/msi/*.msi
          retention-days: 30
